import type { Diagram } from '../model/types'

export const threeDimensionalExample: Diagram = {
  version: 1,
  ambientDimension: 3,
  camera: {
    mode: '3d',
    projection: 'orthographic',
    xVector: [1, 0],
    yVector: [0.45, 0.25],
    zVector: [0, 1],
    scale: 1,
    origin: { x: 0, y: 0 },
  },
  strata: [
    {
      id: 'blueSheet',
      codim: 1,
      geometricKind: 'sheet',
      kind: 'quadSheet',
      name: 'Blue sheet',
      style: {
        kind: 'sheetStyle',
        fillColor: '#4D9DE0',
        fillOpacity: 0.35,
        strokeColor: '#1D6FA5',
        strokeOpacity: 0.9,
      },
      corners: [
        { x: -1, y: -1, z: 0 },
        { x: 2, y: -1, z: 0 },
        { x: 2, y: 1.25, z: 0 },
        { x: -1, y: 1.25, z: 0 },
      ],
      layer: 0,
    },
    {
      id: 'roseSheet',
      codim: 1,
      geometricKind: 'sheet',
      kind: 'quadSheet',
      name: 'Rose sheet',
      style: {
        kind: 'sheetStyle',
        fillColor: '#E76F51',
        fillOpacity: 0.22,
        strokeColor: '#9D3D2F',
        strokeOpacity: 0.8,
      },
      corners: [
        { x: -0.5, y: 0.2, z: -0.5 },
        { x: 1.5, y: 0.2, z: -0.5 },
        { x: 1.5, y: 0.2, z: 1.7 },
        { x: -0.5, y: 0.2, z: 1.7 },
      ],
      layer: 1,
    },
    {
      id: 'solidLine',
      codim: 2,
      geometricKind: 'curve',
      kind: 'polyline',
      name: 'Solid line defect',
      style: {
        kind: 'curveStyle',
        strokeColor: '#111111',
        strokeOpacity: 1,
        lineWidth: 1.2,
        lineStyle: 'solid',
      },
      points: [
        { x: -0.75, y: -0.75, z: 0.15 },
        { x: 0.25, y: -0.1, z: 0.65 },
        { x: 1.5, y: 0.85, z: 1.1 },
      ],
      styleSegments: [],
      layer: 2,
    },
    {
      id: 'hiddenLine',
      codim: 2,
      geometricKind: 'curve',
      kind: 'polyline',
      name: 'Hidden line defect',
      style: {
        kind: 'curveStyle',
        strokeColor: '#C44536',
        strokeOpacity: 0.85,
        lineWidth: 1.3,
        lineStyle: 'denselyDotted',
      },
      points: [
        { x: -0.5, y: 1.1, z: 0.2 },
        { x: 0.6, y: 0.3, z: 1.25 },
        { x: 1.8, y: -0.7, z: 0.55 },
      ],
      styleSegments: [],
      layer: 3,
    },
    {
      id: 'circleJunction',
      codim: 3,
      geometricKind: 'point',
      name: 'Circle junction',
      style: {
        kind: 'pointStyle',
        color: '#000000',
        opacity: 1,
        shape: 'circle',
        fill: 'filled',
        size: 3,
      },
      position: { x: 0.25, y: -0.1, z: 0.65 },
      layer: 4,
    },
    {
      id: 'squareJunction',
      codim: 3,
      geometricKind: 'point',
      name: 'Square junction',
      style: {
        kind: 'pointStyle',
        color: '#6A4C93',
        opacity: 0.95,
        shape: 'square',
        fill: 'hollow',
        size: 4,
      },
      position: { x: 0.6, y: 0.3, z: 1.25 },
      layer: 5,
    },
    {
      id: 'triangleJunction',
      codim: 3,
      geometricKind: 'point',
      name: 'Triangle junction',
      style: {
        kind: 'pointStyle',
        color: '#2A9D8F',
        opacity: 1,
        shape: 'triangle',
        fill: 'filled',
        size: 4,
      },
      position: { x: 1.5, y: 0.85, z: 1.1 },
      layer: 6,
    },
    {
      id: 'starJunction',
      codim: 3,
      geometricKind: 'point',
      name: 'Star junction',
      style: {
        kind: 'pointStyle',
        color: '#F4A261',
        opacity: 1,
        shape: 'star',
        fill: 'hollow',
        size: 5,
      },
      position: { x: 1.8, y: -0.7, z: 0.55 },
      layer: 7,
    },
  ],
  labels: [
    {
      id: 'sheetLabel',
      geometricKind: 'label',
      name: 'Sheet label',
      text: '$\\Sigma$',
      position: { x: -0.8, y: -0.9, z: 0.05 },
      style: {
        kind: 'labelStyle',
        color: '#1D6FA5',
        opacity: 1,
        fontSize: 11,
        anchor: 'south west',
      },
      layer: 10,
    },
    {
      id: 'lineLabel',
      geometricKind: 'label',
      name: 'Line label',
      text: '$F^{(1)}L$',
      position: { x: 0.8, y: 0.15, z: 1.45 },
      style: {
        kind: 'labelStyle',
        color: '#C44536',
        opacity: 1,
        fontSize: 10,
        anchor: 'north',
      },
      layer: 11,
    },
  ],
}
