import type { Diagram } from '../model/types'

export const twoDimensionalExample: Diagram = {
  version: 1,
  ambientDimension: 2,
  camera: {
    mode: '2d',
    scale: 1,
    origin: { x: 0, y: 0 },
  },
  strata: [
    {
      id: 'visibleWire',
      codim: 1,
      geometricKind: 'curve',
      kind: 'polyline',
      name: 'Visible wire',
      style: {
        kind: 'curveStyle',
        strokeColor: '#1A1A1A',
        strokeOpacity: 1,
        lineWidth: 1.2,
        lineStyle: 'solid',
      },
      points: [
        { x: -2, y: 0, z: 0 },
        { x: -0.75, y: 1, z: 0 },
        { x: 0.5, y: 0.2, z: 0 },
        { x: 2, y: 1, z: 0 },
      ],
      styleSegments: [],
      layer: 0,
    },
    {
      id: 'hiddenWire',
      codim: 1,
      geometricKind: 'curve',
      kind: 'polyline',
      name: 'Densely dotted overlap',
      style: {
        kind: 'curveStyle',
        strokeColor: '#C44536',
        strokeOpacity: 0.85,
        lineWidth: 1.4,
        lineStyle: 'denselyDotted',
      },
      points: [
        { x: -2, y: -0.8, z: 0 },
        { x: -0.6, y: -0.1, z: 0 },
        { x: 0.7, y: -0.65, z: 0 },
        { x: 2, y: 0.1, z: 0 },
      ],
      styleSegments: [],
      layer: 1,
    },
    {
      id: 'dashedMorphism',
      codim: 1,
      geometricKind: 'curve',
      kind: 'cubicBezier',
      name: 'Dashed morphism',
      style: {
        kind: 'curveStyle',
        strokeColor: '#2E86AB',
        strokeOpacity: 0.9,
        lineWidth: 1,
        lineStyle: 'dashed',
      },
      points: [
        { x: -1.8, y: 1.6, z: 0 },
        { x: -0.7, y: 2.3, z: 0 },
        { x: 0.8, y: 0.9, z: 0 },
        { x: 1.8, y: 1.6, z: 0 },
      ],
      styleSegments: [],
      layer: 2,
    },
    {
      id: 'circlePoint',
      codim: 2,
      geometricKind: 'point',
      name: 'Filled circle',
      style: {
        kind: 'pointStyle',
        color: '#000000',
        opacity: 1,
        shape: 'circle',
        fill: 'filled',
        size: 3,
      },
      position: { x: -0.75, y: 1, z: 0 },
      layer: 3,
    },
    {
      id: 'squarePoint',
      codim: 2,
      geometricKind: 'point',
      name: 'Hollow square',
      style: {
        kind: 'pointStyle',
        color: '#6A4C93',
        opacity: 1,
        shape: 'square',
        fill: 'hollow',
        size: 4,
      },
      position: { x: 0.5, y: 0.2, z: 0 },
      layer: 4,
    },
    {
      id: 'trianglePoint',
      codim: 2,
      geometricKind: 'point',
      name: 'Filled triangle',
      style: {
        kind: 'pointStyle',
        color: '#2A9D8F',
        opacity: 0.9,
        shape: 'triangle',
        fill: 'filled',
        size: 4,
      },
      position: { x: -0.6, y: -0.1, z: 0 },
      layer: 5,
    },
    {
      id: 'starPoint',
      codim: 2,
      geometricKind: 'point',
      name: 'Hollow star',
      style: {
        kind: 'pointStyle',
        color: '#F4A261',
        opacity: 1,
        shape: 'star',
        fill: 'hollow',
        size: 5,
      },
      position: { x: 0.7, y: -0.65, z: 0 },
      layer: 6,
    },
  ],
  labels: [
    {
      id: 'plainObjectLabel',
      geometricKind: 'label',
      name: 'Object label',
      text: 'C',
      position: { x: -2.25, y: 0.35, z: 0 },
      style: {
        kind: 'labelStyle',
        color: '#000000',
        opacity: 1,
        fontSize: 10,
        anchor: 'center',
      },
      layer: 10,
    },
    {
      id: 'mathMorphismLabel',
      geometricKind: 'label',
      name: 'Math morphism label',
      text: '$F^{(1)}L$',
      position: { x: 0.15, y: 1.75, z: 0 },
      style: {
        kind: 'labelStyle',
        color: '#2E86AB',
        opacity: 1,
        fontSize: 11,
        anchor: 'south',
      },
      layer: 11,
    },
  ],
}
