import assert from 'node:assert/strict'
import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { geometricShapeGroup as group, geometricShapeManifest, geometricBodyVariants,
  geometricShapeArtifacts, assertGeometricShapeEvidence, assertVisibilityCameraPreparation } from './pointGeometricShapesContract.mjs'
import { createOwnedAppPage } from './ownedAppPage.mjs'
import { ownPageEvent } from './ownedPageEvent.mjs'
import { resolvePointInspectorField } from './pointInspectorFields.mjs'
import { boundedPointDiagnostic, createPointDiagnostics } from './pointCheckDiagnostics.mjs'
import { selectGeometricPoint } from './pointGeometricSelection.mjs'
import { dragSelectedPoint } from './pointNativeDrag.mjs'
import { selectHiddenPointVisibility, inspectSourceHiddenPoints } from './pointSourceVisibility.mjs'

const paint = { text: { color: '#000000', opacity: 1 }, fill: { enabled: true, color: '#e0f0ff', opacity: 1 },
  stroke: { enabled: true, color: '#203040', opacity: 1, width: .4, lineStyle: 'solid', dashPhase: 0, lineCap: 'butt', lineJoin: 'miter' } }
const parameterLabels = { aspect: 'Aspect', borderRotate: 'Shape border rotate', borderUsesIncircle: 'Shape border uses incircle',
  regularPolygonSides: 'Regular polygon sides', starPoints: 'Star points', starPointMode: 'Star point mode', starPointHeight: 'Star point height',
  trapeziumLeftAngle: 'Trapezium left angle', trapeziumRightAngle: 'Trapezium right angle', trapeziumStretches: 'Trapezium stretches',
  trapeziumStretchesBody: 'Trapezium stretches body', isoscelesTriangleApexAngle: 'Isosceles triangle apex angle',
  isoscelesTriangleStretches: 'Isosceles triangle stretches', kiteUpperVertexAngle: 'Kite upper vertex angle', kiteLowerVertexAngle: 'Kite lower vertex angle',
  dartTipAngle: 'Dart tip angle', dartTailAngle: 'Dart tail angle', circularSectorAngle: 'Circular sector angle',
  cylinderUsesCustomFill: 'Cylinder uses custom fill', cylinderEndFill: 'Cylinder end fill', cylinderBodyFill: 'Cylinder body fill' }

// Measurements come from connected production SVG and native geometry APIs.
// No expected contour is generated by the solver under test in this harness.
export async function observeGeometricPoint(page, id) {
  return page.evaluate((id) => {
    const outer = document.querySelector(`[data-point-id="${CSS.escape(id)}"]`)
    const node = outer?.querySelector('[data-point-node]')
    if (!node) return null
    const contour = node.querySelector('[data-point-contour]'), body = node.querySelector('[data-label-state]')
    const bounds = contour.getBBox(), ink = body.getBBox(), matrix = contour.getScreenCTM(), local = node.getCTM().inverse().multiply(body.getCTM())
    const at = contour.getPointAtLength(contour.getTotalLength() * .23).matrixTransform(matrix)
    const center = new DOMPoint().matrixTransform(node.getScreenCTM())
    const opacityAncestors = []
    for (let element = contour; element; element = element.parentElement) {
      opacityAncestors.push({ tag: element.localName, opacity: getComputedStyle(element).opacity,
        attributeOpacity: element.getAttribute('opacity'), isPointOwner: element === outer,
        pointId: element.getAttribute('data-point-id'), connected: element.isConnected })
    }
    const clean = (element) => ({ tag: element.localName, attributes: Object.fromEntries([...element.attributes]
      .filter(({ name }) => !name.startsWith('data-') && name !== 'pointer-events').map(({ name, value }) => [name, value])) })
    const contained = []
    if (body.getAttribute('data-label-source')) for (const x of [ink.x, ink.x + ink.width]) for (const y of [ink.y, ink.y + ink.height]) {
      const point = new DOMPoint(x, y).matrixTransform(local)
      contained.push({ x: point.x, y: point.y, inside: contour.isPointInFill(point) || contour.isPointInStroke(point) })
    }
    return { id: outer.getAttribute('data-point-id'), pointVisibility: outer.getAttribute('data-point-visibility'),
      occludingSurfaceId: outer.getAttribute('data-occluding-surface-id'),
      source: body.getAttribute('data-label-source'), state: body.getAttribute('data-label-state'),
      shape: node.getAttribute('data-point-shape'), parameters: JSON.parse(node.getAttribute('data-point-shape-parameters')),
      bounds: { x: bounds.x, y: bounds.y, width: bounds.width, height: bounds.height },
      contourLength: contour.getTotalLength(), contour: clean(contour),
      paintRegions: [...node.querySelectorAll('[data-point-paint-region]')].map((element) => ({ role: element.getAttribute('data-point-paint-region'), ...clean(element) })),
      math: body.querySelectorAll('[data-label-math]').length, bodyUpright: Math.abs(local.b) < 1e-10 && Math.abs(local.c) < 1e-10,
      bodyCorners: contained, center: { x: center.x, y: center.y }, boundary: { x: at.x, y: at.y }, outerOpacity: outer.getAttribute('opacity'),
      effectiveFillOpacity: Number(getComputedStyle(contour).fillOpacity), opacityAncestors,
      effectiveOpacity: Number(getComputedStyle(contour).fillOpacity)
        * opacityAncestors.reduce((product, { opacity }) => product * Number(opacity), 1),
      request: node.getAttribute('data-point-request') }
  }, id)
}

export async function runPointNodeGeometricShapeChecks({ browser, origin, artifactDir, record, observe, startGroup, completeGroup, setStage }) {
  // Explicit context ownership permits standalone pages without browser.newPage's
  // owned-context lifetime restriction. Every page's asynchronous errors survive.
  const ownedContext = await browser.newContext({ viewport: { width: 1700, height: 1300 }, acceptDownloads: true })
  const pageErrors = []
  ownedContext.on('page', (page) => { page.on('pageerror', (error) => pageErrors.push(error.message)); page.on('crash', () => pageErrors.push('Owned browser page crashed')) })
  const page = await ownedContext.newPage(), url = `${origin}/stratified-tikz/scripts/fixtures/freeLabelsApp.html`
  const app = createOwnedAppPage({ page, expectedUrl: url, artifactDir, prefix: 'point-geometric-app' })
  let scenario = 'point-geometric-ellipse', primary
  let selectionSequence = 0
  const selectionDiagnostic = createPointDiagnostics({ artifactDir, observe, artifactPrefix: 'point-geometric-selection' })
  const dragDiagnostic = createPointDiagnostics({ artifactDir, observe, artifactPrefix: 'point-geometric-drag' })
  const visibilityDiagnostic = createPointDiagnostics({ artifactDir, observe, artifactPrefix: 'point-geometric-visibility-control' })
  const waits = [], held = new Set()
  const state = () => app.readState()
  const settle = () => page.waitForFunction(() => !document.querySelector('[data-label-state="pending"]'), undefined, { timeout: 30_000 })
  const model = async () => JSON.parse((await state()).json).diagram
  async function event(name, kind, action) { const wait = ownPageEvent(page, kind, { name, timeoutMs: 30_000 }); waits.push(wait); return wait.run(action) }
  async function load(json) {
    const before = await state()
    const result = await event('geometric-load', 'filechooser', () => page.getByRole('button', { name: 'Load JSON', exact: true }).click())
    await result.event.setFiles({ name: 'geometric.json', mimeType: 'application/json', buffer: Buffer.from(json) })
    await page.waitForFunction((revision) => window.stzAppLabels.state().labelDocumentRevision > revision, before.labelDocumentRevision)
  }
  async function document(spec, source, ambientDimension = 2, configured = false) {
    const input = JSON.parse(await page.evaluate(({ ambientDimension, source }) => window.stzAppLabels.pointDocumentJson(ambientDimension, source), { ambientDimension, source }))
    const point = input.diagram.strata[0]
    point.position = { x: 3, y: 3, z: 0 }
    point.style = { ...point.style, shape: spec.shape, opacity: 1, size: 8, paint: structuredClone(paint),
      ...(configured ? { shapeParameters: spec.parameters } : {}) }
    if (spec.shape === 'cylinder' && configured) point.style.paint.fill.enabled = false
    return input
  }
  async function select(id = 'app-point', boundary = false) {
    const rendered = await selectGeometricPoint({ page, readState: state, observePoint: observeGeometricPoint,
      diagnose: (details) => selectionDiagnostic(group, scenario, details), secondaryErrors: pageErrors,
      scenario, sequence: ++selectionSequence, id, boundary, requireUnselected: !boundary })
    const beforeInspector = await state()
    const open = page.getByRole('button', { name: 'Open inspector drawer', exact: true })
    if (await open.count()) await open.click()
    const expand = page.locator('#preview-inspector-drawer').getByRole('button', { name: 'Expand', exact: true })
    if (await expand.count()) await expand.click()
    const afterInspector = await state()
    await boundedPointDiagnostic(() => selectionDiagnostic(group, scenario, { boundary: 'inspector-reopened',
      sequence: selectionSequence, beforeInspector, afterInspector }), 'Geometric Inspector reopening evidence')
    for (const field of ['json', 'runtimeDiagramJson', 'history', 'labelDocumentRevision']) {
      assert.equal(afterInspector[field], beforeInspector[field], `Native Inspector reopening preserves ${field}`)
    }
    return rendered
  }
  async function colorParameter(key, value, label) {
    const caption = `${label} hex`, token = `${scenario}:${key}`
    const control = await resolvePointInspectorField(page, caption, 'input[type="text"]')
    let primary
    try {
      await control.evaluate((element, token) => {
        const registry = window.__stzGeometricColorInputs ??= new Map()
        if (registry.has(token)) throw new Error(`Color observation is already owned: ${token}`)
        const owned = { element, beforeValue: element.value, inputType: element.type, events: [] }
        owned.listener = (event) => owned.events.push({ type: event.type, trusted: event.isTrusted, value: element.value })
        registry.set(token, owned)
        element.addEventListener('input', owned.listener)
      }, token)
      try { await control.fill(value, { timeout: 5000 }) } catch (error) { primary = error }
      let observation
      try {
        observation = await page.evaluate((token) => {
          const owned = window.__stzGeometricColorInputs.get(token)
          return { inputType: owned.inputType, beforeValue: owned.beforeValue,
            finalInputType: owned.element.type, finalValue: owned.element.value, events: [...owned.events] }
        }, token)
        observation = { parameter: key, caption, expectedValue: value, ...observation,
          finalModelValue: (await model()).strata[0].style.shapeParameters?.[key],
          ...(primary ? { actionError: { message: primary.message, stack: primary.stack } } : {}) }
        // Keep raw native events and values before any success assertion.
        await observe(`${scenario}-${key}-native-input`, { group, observation })
      } catch (error) {
        if (primary) pageErrors.push(`Color observation after primary failure: ${error.message}`)
        throw primary ?? error
      }
      if (primary) throw primary
      assert.equal(observation.inputType, 'text', `${key}: native hexadecimal text input`)
      assert.equal(observation.finalInputType, 'text', `${key}: control remains a text input`)
      assert.equal(observation.beforeValue.toLowerCase(), '#ffffff', `${key}: actual default input`)
      assert.notEqual(observation.beforeValue.toLowerCase(), value.toLowerCase(), `${key}: edit changes the default`)
      assert.ok(observation.events.length > 0, `${key}: native input event was observed`)
      assert.ok(observation.events.every((event) => event.type === 'input' && event.trusted === true),
        `${key}: all observed input events are trusted`)
      const finalInput = observation.events.at(-1)
      assert.equal(finalInput.type, 'input'); assert.equal(finalInput.trusted, true)
      assert.equal(finalInput.value, value)
      assert.equal(observation.finalValue, value)
      assert.equal(observation.finalModelValue, value)
      return observation
    } catch (error) { primary ??= error; throw primary }
    finally {
      try {
        await page.evaluate((token) => {
          const registry = window.__stzGeometricColorInputs, owned = registry?.get(token)
          if (owned) owned.element.removeEventListener('input', owned.listener)
          registry?.delete(token)
          if (registry?.size === 0) delete window.__stzGeometricColorInputs
        }, token)
      } catch (error) {
        if (!primary) throw error
        pageErrors.push(`Color input listener cleanup: ${error.message}`)
      }
    }
  }
  async function parameters(spec) {
    const nativeColorInputs = []
    for (const [key, value] of Object.entries(spec.parameters)) {
      const label = parameterLabels[key]
      if (typeof value === 'string' && key !== 'starPointMode') {
        nativeColorInputs.push(await colorParameter(key, value, label))
      } else {
        const selector = typeof value === 'boolean' ? 'input[type="checkbox"]' : key === 'starPointMode' ? 'select' : 'input[type="text"]'
        const control = await resolvePointInspectorField(page, label, selector)
        if (typeof value === 'boolean') await control.setChecked(value)
        else if (key === 'starPointMode') await control.selectOption(value)
        else await control.fill(String(value))
      }
      assert.equal((await model()).strata[0].style.shapeParameters[key], value, `Native parameter ${key}`)
    }
    return nativeColorInputs
  }
  async function save(details) {
    const evidence = { scenario, group, result: 'passed', pageErrors: [...pageErrors], ...details }
    assertGeometricShapeEvidence(evidence, scenario)
    await writeFile(resolve(artifactDir, `${scenario}.json`), JSON.stringify(evidence, null, 2) + '\n')
    await record(scenario, { group, result: 'passed', artifacts: geometricShapeArtifacts(scenario) })
  }
  try {
    setStage?.(group); await startGroup(group)
    await app.install(); await page.goto(url); await app.start()
    for (const spec of geometricShapeManifest) {
      scenario = `point-geometric-${spec.slug}`
      const cases = []
      // Native shape and parameter controls commit through real React handlers.
      const initial = await document({ shape: 'circle' }, 'native shape')
      await load(JSON.stringify(initial)); await settle(); await select()
      await (await resolvePointInspectorField(page, 'Shape', 'select')).selectOption(spec.shape)
      assert.equal((await model()).strata[0].style.shape, spec.shape)
      const nativeColorInputs = await parameters(spec)
      const configuredStyle = structuredClone((await model()).strata[0].style)
      for (const mode of ['default', 'configured']) for (const body of geometricBodyVariants) {
        const input = await document(spec, body.source, 2, mode === 'configured')
        if (mode === 'configured') input.diagram.strata[0].style = { ...configuredStyle, paint: input.diagram.strata[0].style.paint }
        await load(JSON.stringify(input))
        const before = await state(); await settle()
        const rendered = await observeGeometricPoint(page, 'app-point'), after = await state()
        assert.ok(rendered)
        assert.ok(rendered.bodyCorners.every(({ inside }) => inside), `${spec.shape}/${mode}/${body.key}: body glyph box is enclosed`)
        const entry = { mode, body: body.key, source: body.source, rendered,
          modelUnchanged: before.json === after.json && before.history === after.history }
        cases.push(entry)
        await observe(`${scenario}-${mode}-${body.key}`, { group, entry })
      }
      await save({ shape: spec.shape, parameters: spec.parameters, cases, nativeShapeControl: true, nativeStyle: configuredStyle, nativeColorInputs })
    }
    scenario = 'point-geometric-native-contours-2d-3d'
    const interactions = []
    for (const ambientDimension of [2, 3]) for (const shape of ['diamond', 'star', 'semicircle', 'dart']) {
      const spec = geometricShapeManifest.find((entry) => entry.shape === shape)
      await load(JSON.stringify(await document(spec, 'drag $x_i$', ambientDimension, true))); await settle()
      const observed = await select('app-point', true), before = (await model()).strata[0]
      const nativeDrag = await dragSelectedPoint({ page, readState: state,
        diagnose: (details) => dragDiagnostic(group, scenario, details), secondaryErrors: pageErrors,
        scenario, sequence: selectionSequence, id: 'app-point', displacement: { x: 28, y: -16 }, steps: 4 })
      const after = (await model()).strata[0]
      const events = nativeDrag.afterAction.observation.events.filter(({ phase }) => phase === 'drag')
      interactions.push({ ambientDimension, shape, codim: before.codim, selected: true, observed, before, after, events, nativeDrag,
        trustedDown: events.some(({ type, trusted }) => type === 'pointerdown' && trusted), trustedMove: events.some(({ type, trusted }) => type === 'pointermove' && trusted),
        dragged: true, undoRestored: true, redoRestored: true })
    }
    await save({ cases: interactions })

    scenario = 'point-geometric-visibility'
    const visibilityDoc = await document(geometricShapeManifest.find(({ shape }) => shape === 'dart'), '$locked$')
    visibilityDoc.diagram.layers = [{ value: 0, name: 'locked', visible: true, locked: true }]
    await load(JSON.stringify(visibilityDoc)); await settle()
    const locked = await observeGeometricPoint(page, 'app-point'), beforeLocked = await state()
    await page.getByRole('button', { name: 'Select', exact: true }).click(); await page.mouse.click(locked.boundary.x, locked.boundary.y)
    const lockedState = await state()
    visibilityDoc.diagram.layers[0] = { value: 0, name: 'hidden', visible: false }
    await load(JSON.stringify(visibilityDoc)); await settle()
    const hidden = { state: await state(), rendered: await observeGeometricPoint(page, 'app-point') }
    const hiddenAbsent = hidden.rendered === null
    const dim = await document(geometricShapeManifest.find(({ shape }) => shape === 'semicircle'), '$dimmed$', 3)
    dim.diagram.strata[0].position = { x: 0, y: -1, z: 0 }
    dim.diagram.camera = { mode: '3d', kind: 'orthographic', thetaDeg: 90, phiDeg: 0, zoom: 100, pan: { x: 450, y: 350 } }
    dim.diagram.strata.push({ id: 'occluder', codim: 1, geometricKind: 'sheet', kind: 'quadSheet', name: 'Occluding sheet', layer: 0,
      corners: [{ x: -2, y: 0, z: -2 }, { x: 2, y: 0, z: -2 }, { x: 2, y: 0, z: 2 }, { x: -2, y: 0, z: 2 }],
      style: { kind: 'sheetStyle', fillColor: '#4D9DE0', fillOpacity: .35, strokeColor: '#4D9DE0', strokeOpacity: 1 } })
    await load(JSON.stringify(dim)); await settle()
    const cameraFields = [['theta value', '90'], ['phi value', '0']]
    const cameraObservation = async (label) => {
      const locator = page.locator('.camera-panel').getByRole('spinbutton', { name: label, exact: true })
      const controls = await locator.evaluateAll((elements) => elements.map((element) => {
        const bounds = element.getBoundingClientRect(), style = getComputedStyle(element)
        return { tag: element.localName, type: element.type, value: element.value, connected: element.isConnected,
          visible: bounds.width > 0 && bounds.height > 0 && style.display !== 'none' && style.visibility !== 'hidden',
          enabled: !element.matches(':disabled') && element.getAttribute('aria-disabled') !== 'true',
          ariaLabel: element.getAttribute('aria-label'), scope: element.closest('.camera-panel') ? '.camera-panel' : null }
      }))
      return { label, count: await locator.count(), ...controls[0], controls }
    }
    // Saved view.camera3d takes precedence over diagram.camera during native
    // load. Apply the intended occlusion orientation through actual controls.
    const cameraPreparation = { before: await state(),
      controlsBefore: await Promise.all(cameraFields.map(([label]) => cameraObservation(label))),
      renderedBefore: await observeGeometricPoint(page, 'app-point'), actions: [] }
    await visibilityDiagnostic(group, scenario, { phase: 'visibility-camera-before', cameraPreparation })
    if (cameraPreparation.controlsBefore.some(({ count }) => count === 0)) {
      const toggle = page.locator('.camera-panel .camera-summary-toggle')
      const expansion = { before: await state(), count: await toggle.count(), expandedBefore: await toggle.getAttribute('aria-expanded') }
      cameraPreparation.expansion = expansion
      assert.equal(expansion.count, 1, 'One camera details toggle')
      assert.equal(expansion.expandedBefore, 'false', 'Absent camera fields belong to collapsed details')
      await toggle.click({ timeout: 5000 })
      expansion.stateAfter = await state(); expansion.expandedAfter = await toggle.getAttribute('aria-expanded')
      await visibilityDiagnostic(group, scenario, { phase: 'visibility-camera-expanded', expansion })
      assert.equal(expansion.expandedAfter, 'true', 'Native camera details opened')
    }
    for (const [label, value] of cameraFields) {
      const action = { label, value, before: { state: await state(), control: await cameraObservation(label) } }
      await visibilityDiagnostic(group, scenario, { phase: 'visibility-camera-field-before', action })
      assert.equal(action.before.control.count, 1, `One native ${label}`)
      for (const key of ['connected', 'visible', 'enabled']) assert.equal(action.before.control[key], true, `Usable ${label}: ${key}`)
      let cameraError
      try { await page.locator('.camera-panel').getByRole('spinbutton', { name: label, exact: true }).fill(value, { timeout: 5000 }) }
      catch (error) { cameraError = error }
      try {
        action.after = { state: await boundedPointDiagnostic(state, 'Visibility camera authoritative state'),
          control: await boundedPointDiagnostic(() => cameraObservation(label), 'Visibility camera native field') }
        await boundedPointDiagnostic(() => visibilityDiagnostic(group, scenario, { phase: 'visibility-camera-field-after', action,
          ...(cameraError ? { actionError: { message: cameraError.message, stack: cameraError.stack } } : {}) }),
        'Visibility camera after-action evidence')
      } catch (error) {
        if (cameraError) pageErrors.push(`Visibility camera observation after primary failure: ${error.message}`)
        throw cameraError ?? error
      }
      if (cameraError) throw cameraError
      assert.equal(action.after.control.value, value, `Actual native ${label} value`)
      cameraPreparation.actions.push(action)
    }
    cameraPreparation.after = await state()
    cameraPreparation.controlsAfter = await Promise.all(cameraFields.map(([label]) => cameraObservation(label)))
    cameraPreparation.renderedAfter = await observeGeometricPoint(page, 'app-point')
    await visibilityDiagnostic(group, scenario, { phase: 'visibility-camera-after', cameraPreparation })
    assertVisibilityCameraPreparation(cameraPreparation)
    const actualCamera = JSON.parse(cameraPreparation.after.uiSettings).camera3d
    assert.equal(actualCamera.thetaDeg, 90, 'Authoritative front-view theta')
    assert.equal(actualCamera.phiDeg, 0, 'Authoritative front-view phi')
    const approximate = page.locator('.source-panel').getByLabel('Enable approximate 3D visibility', { exact: true })
    const checkboxObservation = async () => {
      const controls = await approximate.evaluateAll((elements) => elements.map((element) => ({
        tag: element.localName, type: element.type, checked: element.checked, connected: element.isConnected,
        enabled: !element.matches(':disabled') && element.getAttribute('aria-disabled') !== 'true',
        scope: element.closest('.source-panel') ? '.source-panel' : null,
        labels: Array.from(element.labels ?? [], (label) => ({ text: label.textContent, outerHTML: label.outerHTML })),
      })))
      return { count: await approximate.count(), ...controls[0], controls }
    }
    const enable = { before: await state(), checkboxBefore: await checkboxObservation(),
      controlBefore: await inspectSourceHiddenPoints(page) }
    await visibilityDiagnostic(group, scenario, { phase: 'approximate-visibility-before', enable })
    assert.equal(JSON.parse(enable.before.runtimeDiagramJson).ambientDimension, 3, 'Approximate visibility requires 3D')
    assert.equal(enable.checkboxBefore.count, 1, 'One source-panel approximate visibility checkbox')
    assert.equal(enable.checkboxBefore.connected, true, 'Connected approximate visibility checkbox')
    assert.equal(enable.checkboxBefore.enabled, true, 'Enabled approximate visibility checkbox')
    let enableError
    try { await approximate.check({ timeout: 5000 }) } catch (error) { enableError = error }
    try {
      enable.after = await boundedPointDiagnostic(state, 'Visibility enabled authoritative state')
      enable.checkbox = await boundedPointDiagnostic(checkboxObservation, 'Visibility enabled checkbox')
      enable.controlAfter = await boundedPointDiagnostic(() => inspectSourceHiddenPoints(page), 'Visibility enabled native control')
      await boundedPointDiagnostic(() => visibilityDiagnostic(group, scenario,
        { phase: 'approximate-visibility-after', enable,
          ...(enableError ? { actionError: { message: enableError.message, stack: enableError.stack } } : {}) }),
      'Approximate visibility after-action evidence')
    } catch (error) {
      if (enableError) pageErrors.push(`Visibility enabled observation after primary failure: ${error.message}`)
      throw enableError ?? error
    }
    if (enableError) throw enableError
    assert.equal(enable.checkbox.checked, true, 'Real approximate visibility checkbox is checked')
    assert.equal(JSON.parse(enable.after.uiSettings).visibility.enabled, true, 'Authoritative approximate visibility is enabled')
    const actions = []
    // The initial dimHidden selection may be a no-op. Exercise both values
    // through the same native field, retaining each actual state and render.
    for (const [index, value] of ['dimHidden', 'hideHidden', 'dimHidden'].entries()) {
      actions.push(await selectHiddenPointVisibility({ page, readState: state, observePoint: observeGeometricPoint,
        diagnose: (details) => visibilityDiagnostic(group, scenario, details), secondaryErrors: pageErrors,
        scenario, sequence: index + 1, value, id: 'app-point' }))
    }
    const dimmed = actions.at(-1).afterAction.rendered
    await save({ hiddenAbsent, lockedUnchanged: beforeLocked.json === lockedState.json,
      lockedNotSelected: lockedState.selection?.id !== 'app-point', dimmedVisible: !!dimmed,
      dimmedOpacity: dimmed?.effectiveFillOpacity > 0 && dimmed.effectiveFillOpacity < 1
        && dimmed.effectiveOpacity > 0 && dimmed.effectiveOpacity < 1, locked, dimmed,
      visibility: { locked: { before: beforeLocked, stateAfter: lockedState, rendered: locked }, hidden, cameraPreparation, enable, actions } })

    for (const background of ['transparent', 'white']) {
      scenario = `point-geometric-download-${background}`
      const source = `captured ${background} $\\frac{x_1}{y^2}$`
      const input = await document(geometricShapeManifest[0], source)
      const template = input.diagram.strata[0]
      input.diagram.strata = geometricShapeManifest.map((spec, index) => ({ ...structuredClone(template), id: `geometric-${spec.slug}`,
        text: index === 0 ? source : `${spec.slug} $x_i$`, position: { x: (index % 4) * 4, y: 9 - Math.floor(index / 4) * 4, z: 0 },
        style: { ...structuredClone(template.style), shape: spec.shape, shapeParameters: spec.parameters,
          paint: { ...structuredClone(paint), fill: { ...paint.fill, enabled: spec.shape !== 'cylinder' } } } }))
      await page.evaluate((source) => window.stzAppLabels.hold(source), source); held.add(source)
      await load(JSON.stringify(input))
      await page.waitForFunction((source) => window.stzAppLabels.pending(source)?.started > 0, source)
      await select('geometric-ellipse')
      await page.getByLabel('SVG export background', { exact: true }).selectOption(background)
      await page.evaluate((ids) => window.stzAppLabels.armPointExportClick(ids), input.diagram.strata.map(({ id }) => id))
      let click
      const { event: download } = await event(scenario, 'download', async ({ check }) => {
        await page.getByRole('button', { name: 'Export current diagram view as SVG', exact: true }).click(); check()
        click = await page.evaluate(() => window.stzAppLabels.pointExportClick())
        assert.equal(click.error, undefined)
        await (await resolvePointInspectorField(page, 'Node text', 'textarea')).fill('later $changed$')
        await (await resolvePointInspectorField(page, 'Shape', 'select')).selectOption('diamond')
        await (await resolvePointInspectorField(page, 'Aspect', 'input[type="text"]')).fill('2.5')
        check(); await page.evaluate((source) => window.stzAppLabels.release(source), source); held.delete(source)
      })
      const svgPath = resolve(artifactDir, `${scenario}.svg`); await download.saveAs(svgPath)
      const xml = await readFile(svgPath, 'utf8')
      assert.ok(xml.includes(source.replaceAll('&', '&amp;').replaceAll('<', '&lt;')))
      assert.ok(!xml.includes('later $changed$'))
      // Reload original captured inputs and settle, independently of the later
      // editor state, for exact shared-view contour and paint comparison.
      await load(JSON.stringify(input)); await settle()
      const expected = []
      for (const point of input.diagram.strata) expected.push({ id: point.id, source: point.text, shape: point.style.shape,
        rendered: await observeGeometricPoint(page, point.id) })
      const standalone = await ownedContext.newPage(), requests = []
      standalone.on('request', (request) => requests.push(request.url()))
      let reopened, standaloneFailure
      try {
        await standalone.goto(pathToFileURL(svgPath).href)
        reopened = await standalone.evaluate((expected) => {
          const clean = (element) => ({ tag: element.localName, attributes: Object.fromEntries([...element.attributes]
            .filter(({ name }) => !name.startsWith('data-') && name !== 'pointer-events').map(({ name, value }) => [name, value])) })
          return expected.map(({ source, shape }) => {
            const title = [...document.querySelectorAll('title')].find((element) => element.textContent === source)
            if (!title) return { source, missing: true }
            const body = title.parentElement, node = body.parentElement
            const shapes = [...node.children].filter((element) => ['path', 'polygon', 'circle', 'ellipse', 'rect'].includes(element.localName))
            const border = shapes.find((element) => element.getAttribute('stroke') !== 'none' && element.hasAttribute('stroke'))
            return { source, shape, contour: border && clean(border),
              regions: shapes.filter((element) => element.getAttribute('stroke') === 'none').map(clean),
              glyphs: body.querySelectorAll('path,use').length, errors: document.querySelectorAll('parsererror,foreignObject,image,script').length }
          })
        }, expected)
        for (const [index, actual] of reopened.entries()) {
          assert.equal(actual.missing, undefined); assert.equal(actual.errors, 0); assert.ok(actual.glyphs > 0)
          assert.deepEqual(actual.contour, expected[index].rendered.contour)
        }
        const cylinder = reopened.find(({ shape }) => shape === 'cylinder')
        assert.equal(cylinder.regions.length, 2)
        assert.deepEqual(cylinder.regions.map(({ attributes }) => attributes.fill).sort(), ['#99ddff', '#ffcc66'])
        assert.deepEqual(requests.filter((request) => !request.startsWith('file:')), [])
        await standalone.screenshot({ path: resolve(artifactDir, `${scenario}.png`), fullPage: true })
        await writeFile(resolve(artifactDir, `${scenario}-standalone.json`), JSON.stringify({ reopened, requests, pageErrors, expected, click }, null, 2) + '\n')
      } catch (error) { standaloneFailure = error; throw error }
      finally { try { await standalone.close() } catch (error) { if (!standaloneFailure) throw error; pageErrors.push(`Standalone cleanup: ${error.message}`) } }
      const captured = click.snapshot.points
      for (const [index, entry] of captured.entries()) assert.deepEqual(entry.style.shapeParameters, input.diagram.strata[index].style.shapeParameters)
      await save({ background, shapes: geometricShapeManifest.map(({ shape }) => shape), reopened: true, immutableSource: true,
        immutableParameters: true, separateCylinderPaints: true, noExternalAssets: true, actualDownload: true, click, expected })
    }
    assert.deepEqual(pageErrors, []); await completeGroup(group)
  } catch (error) {
    primary = error
    await writeFile(resolve(artifactDir, 'point-geometric-failure.json'), JSON.stringify({ scenario, result: 'failed', pageErrors,
      error: { message: error.message, stack: error.stack } }, null, 2) + '\n')
    try { await app.failure(error, { scenario, pageErrors }) } catch (diagnosticError) {
      await writeFile(resolve(artifactDir, 'point-geometric-diagnostic-failure.json'), JSON.stringify({ primary: error.message, diagnostic: diagnosticError.message }, null, 2) + '\n')
    }
    throw error
  } finally {
    let cleanupFailure
    for (const wait of waits) wait.dispose()
    for (const source of held) { try { await page.evaluate((source) => window.stzAppLabels.release(source), source) } catch (error) { cleanupFailure ??= error; pageErrors.push(`Held conversion cleanup: ${error.message}`) } }
    try { await ownedContext.close() } catch (error) {
      if (!primary) throw error
      await writeFile(resolve(artifactDir, 'point-geometric-secondary-failure.json'), JSON.stringify({ primary: primary.message, cleanup: error.message, pageErrors }, null, 2) + '\n')
    }
    if (!primary && cleanupFailure) throw cleanupFailure
  }
}
