import { mkdir, readFile, readdir, copyFile, writeFile, rm } from 'node:fs/promises'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('../', import.meta.url))
const expectedVersion = '4.1.3'
const packages = [
  ['engine', '@mathjax/src'],
  ['font', '@mathjax/mathjax-newcm-font'],
]

// These generated imports are ordinary module specifiers: Vite sees every
// possible font-data request and rewrites its chunk URL for the configured base.
const fontRoot = join(root, 'node_modules/@mathjax/mathjax-newcm-font')
for (const [, name] of packages) {
  const pkg = JSON.parse(await readFile(join(root, 'node_modules', name, 'package.json'), 'utf8'))
  if (pkg.version !== expectedVersion) throw new Error(`Expected ${name}@${expectedVersion}`)
}
const names = (await readdir(join(fontRoot, 'mjs/svg/dynamic')))
  .filter((name) => name.endsWith('.js')).sort()
if (names.length === 0) throw new Error('MathJax SVG dynamic font data is missing')
const generated = [
  '// Generated by scripts/prepareMathjaxAssets.mjs; do not edit.',
  '// Exact import specifiers keep Node tests and Vite development/build identical.',
  'export const mathjaxFontImports: Readonly<Record<string, () => Promise<unknown>>> = Object.freeze({',
  ...names.map((name) => `  '${name}': () => import('@mathjax/mathjax-newcm-font/js/svg/dynamic/${name}'),`),
  '})',
  '',
].join('\n')
const generatedPath = join(root, 'src/rendering/labels/mathjaxFontImports.generated.ts')
await mkdir(dirname(generatedPath), { recursive: true })
await writeFile(generatedPath, generated)

// No font binaries are needed for path-only SVG. Distribute all upstream
// license files nevertheless, including licenses nested with font resources.
const output = join(root, 'public/mathjax-licenses')
await rm(output, { recursive: true, force: true })
async function copyLicenses(directory, packageRoot, target) {
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const source = join(directory, entry.name)
    if (entry.isDirectory() && entry.name !== 'node_modules') {
      await copyLicenses(source, packageRoot, target)
    } else if (entry.isFile() && /^(license|copying)([.-]|$)/i.test(entry.name)) {
      const destination = join(target, relative(packageRoot, source))
      await mkdir(dirname(destination), { recursive: true })
      await copyFile(source, destination)
    }
  }
}
for (const [directory, name] of packages) {
  const packageRoot = join(root, 'node_modules', name)
  await copyLicenses(packageRoot, packageRoot, join(output, directory))
}
